import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { GitHubBanner } from "@refinedev/core";
import { DevtoolsProvider } from "@providers/devtools";
import { RefineKbarProvider } from "@refinedev/kbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@refinedev/antd/dist/reset.css";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { RefineContext } from "@providers/refine-context";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <Suspense>
      <GitHubBanner />
      <RefineKbarProvider>
        <AntdRegistry>
          <ColorModeContextProvider defaultMode={defaultMode}>
            <DevtoolsProvider>
              <RefineContext>{children}</RefineContext>
            </DevtoolsProvider>
          </ColorModeContextProvider>
        </AntdRegistry>
      </RefineKbarProvider>
    </Suspense>
  );
}
